name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"   # Runs every day at midnight UTC
  workflow_dispatch:       # Allow manual trigger from Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generate the snake.svg
      - name: Generate GitHub Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: abinasharma001
          outputs: dist/github-contribution-grid-snake.svg
          # you can also add: dist/github-contribution-grid-snake-dark.svg --palette github-dark

      # Push the generated files to the `output` branch
      - name: Push Snake to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
