name: GitHub Readme YouTube Cards
on:
  schedule:
    # Runs at 00:00 and 12:00 UTC every day
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DenverCoder1/github-readme-youtube-cards@v3.1.0
        with:
          channel_id: UCoW3NEm3evBxaRAwMNHrY_g
          comment_tag_name: YOUTUBE-CARDS
          youtube_api_key: ${{ secrets.YOUTUBE_API_KEY }}
          show_duration: true
